config/routes.rb
Rails.application.routes.draw do
  resources :insurance_policies
  resources :valuations
  resources :jde_logs
  resources :deadlines
  resources :vehicle_logs
  resources :vehicle_items
  resources :concept_services
  resources :questions
  resources :answers
  resources :catalog_tires_batteries
  resources :ticket_tire_batteries
  resources :parameters
  resources :sections
  get 'budgets/index'
  resources :maintenance_tickets
  resources :maintenance_frecuencies
  resources :agency_mileage_indicators
  resources :workshop_certifications
  resources :review_workshops
  get 'catalog_branches_users/index'
  resources :service_orders
  resources :maintenance_programs
  resources :maintenance_appointments
  resources :mileage_indicators
  resources :maintenance_logs
  resources :mechanical_reviews
  resources :catalog_considerations
  resources :expense_vehicle_types
  resources :tuning_prices
  resources :monthly_yields
  resources :maintenance_controls
  resources :insurance_report_tickets
  resources :catalog_workshops
  resources :consumptions
  resources :accumulated_fuels
  resources :vehicle_consumptions
  resources :budget_administrations
  resources :budget_delivery_replacements
  resources :budget_sales_replacements
  resources :delivery_addresses
  resources :deliveries
  resources :customers
  resources :budget_distributions
  resources :reasons
  resources :purchase_orders
  resources :perform_targets
  resources :accounting_impacts
  resources :competition_tables
  resources :vehicle_indicators
  get 'users', to: "users#index", as: "users"
  post "/create_new_user", to: "users#create_new_user", as: "create_new_user"
  patch "/update", to: "users#update", as: "update"
  # get 'users/destroy'
  
  resources :user_vehicles
  devise_for :users
  resources :type_sinisters
  resources :catalog_responsives
  resources :catalogo_adaptations
  resources :catalog_areas
  resources :fuel_budgets
  resources :vehicle_prices
  resources :vehicle_permits
  
  resources :vehicle_models
  resources :vehicle_checklists
  resources :catalog_branches
  resources :catalog_models
  resources :catalog_brands
  resources :catalog_roles
  resources :catalog_licences
  resources :catalog_personals
  resources :catalog_vendors
  resources :vehicles
  resources :cost_centers
  resources :insurance_beneficiaries
  resources :policy_coverages
  resources :billed_companies
  resources :responsables
  resources :catalog_repairs
  resources :vehicle_statuses
  resources :vehicle_types
  resources :plate_states
  resources :catalog_routes
  resources :budget_concepts
  resources :order_service_types
  resources :vehicle_brands
  resources :branch_offices
  resources :catalog_companies
  resources :movil_api
  resources :warehouses
  #expediente
  post 'uploads/:id', to: "vehicles#uploads",as: "uploads"
  get 'ver_documentos/:id', to: "vehicles#ver_documentos",as: "ver_documentos"
  get 'document_detail/:file_id', to: "vehicles#document_detail",as: "document_detail"

  get 'borrar_firma/:id',to: "parameters#borrar_firma", as: "borrar_firma"
  post 'img_ticket_taller',to: "movil_api#img_ticket_taller"
  get 'ver_ticket_taller/:maintenance_ticket_id',to: "movil_api#ver_ticket_taller"
  post 'bimonthly_img', to: "movil_api#bimonthly_img"
  get 'ver_biomonthly_img/:bimonthly_verification_id', to: "movil_api#bimonthly_img"
  post 'cargar_imagen_licencia', to: "movil_api#cargar_imagen_licencia"
  post 'cargar_imagen_siniestro', to: "movil_api#cargar_imagen_siniestro"
  get 'ver_firma_usuario/:user_id', to: "movil_api#ver_firma_usuario"
  post 'firma_usuario', to: "movil_api#firma_usuario"
  get 'ver_licencias/:user_id', to: "movil_api#ver_licencias"
  get 'ver_evidencia_check/:checklist_response_id', to: "movil_api#ver_evidencia_check"
  
  

  put 'firma_venta/:vehicle_id', to: "movil_api#firma_venta"
  get 'ver_firma_venta/:vehicle_id', to: "movil_api#ver_firma_venta"
  post 'agregar_img_llantas', to: "movil_api#agregar_img_llantas"
  get 'ver_img_llantas/:ticket_tire_battery_id', to: "movil_api#ver_img_llantas"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: 'home#login'
  #Maestro de vehiculos
  root to: "vehicles#index"
  post '/import_vehicles', to: 'vehicles#import_vehicles', as: "import_vehicles"
  get '/template_download_vehicles', to: 'vehicles#template_download_vehicles', as: "template_download_vehicles"
  get 'generar_excel', to: "vehicles#generar_excel", as: "generar_excel"
  get 'cancelar_compra/:id',to: "vehicles#cancelar_compra", as: "cancelar_compra"
  get 'listado_checklist/:id',to: "vehicles#listado_checklist", as: "listado_checklist"
  get 'detalle_checklist/:checklist_id',to: "vehicles#detalle_checklist", as: "detalle_checklist"
  get 'detalle_auditoria/:auditoria_id',to: "vehicles#detalle_auditoria", as: "detalle_auditoria"
  get 'vehicle_expenses/:id',to: "vehicles#vehicle_expenses", as: "vehicle_expenses"
  post 'gastos_vehiculo_x_fecha/:id',to: "vehicles#gastos_vehiculo_x_fecha", as: "gastos_vehiculo_x_fecha"
  #orden de compra
  get 'purchase_orders/:id/imprimir', to: "purchase_orders#imprimir", as: "orden_imprimir"
  get 'documentos_orden/:id', to: "purchase_orders#documentos_orden", as: "documentos_orden"
  post 'cargar_documento_orden', to: "purchase_orders#cargar_documento_orden", as: "cargar_documento_orden"
  get 'factura_orden/:id', to: "purchase_orders#factura_orden", as: "factura_orden"
  post 'cargar_factura_orden', to: "purchase_orders#cargar_factura_orden", as: "cargar_factura_orden"
  post '/filtrado_ordenes', to: "purchase_orders#filtrado_ordenes", as: "filtrado_ordenes"
  get "/nueva_orden", to: "purchase_orders#nueva_orden", as:"nueva_orden"
  post "/crear_orden", to: "purchase_orders#crear_orden", as:"crear_orden"
  get 'formulario_agregar_detalle_orden', to: "purchase_orders#formulario_agregar_detalle_orden", as: "formulario_agregar_detalle_orden"
  post "/guardar_detalle_orden", to: "purchase_orders#guardar_detalle_orden", as:"guardar_detalle_orden"
  post '/guardar_total', to: "purchase_orders#guardar_total", as: "guardar_total"
  get 'eliminar_partida_orden/:id_partida', to:"purchase_orders#eliminar_partida_orden", as: "eliminar_partida_orden"
  get 'purchase_orders/:id/imprimir_orden', to: "purchase_orders#show", as: "imprimir_orden"
  
  #rutas presupuestos para venta
  get "/nuevo_presupuesto", to: "budget_concepts#nuevo_presupuesto", as:"nuevo_presupuesto"
  post "/crear_presupuesto", to: "budget_concepts#crear_presupuesto", as:"crear_presupuesto"
  get 'formulario_agregar_detalle', to: "budget_concepts#formulario_agregar_detalle", as: "formulario_agregar_detalle"
  post "/guardar_detalle", to: "budget_concepts#guardar_detalle", as:"guardar_detalle"
  get 'eliminar_partida/:id_partida', to:"budget_concepts#eliminar_partida", as: "eliminar_partida"
  get 'budget_concepts/:id/imprimir_pres', to: "budget_concepts#show", as: "presupuesto_pdf_imprimir"
  get 'solicitar_presupuesto_venta/:id', to: "budget_concepts#solicitar_presupuesto_venta", as: "solicitar_presupuesto_venta"
  get 'borrar_presupuesto_venta/:id',to: "budget_concepts#borrar_presupuesto_venta", as: "borrar_presupuesto_venta"
  
  # secciones- area
  get "/asignar_area/:id", to: "sections#asignar_area", as:"asignar_area"
  post "/guardar_area/:id", to: "sections#guardar_area", as:"guardar_area"
  get "/ver_areas/:id", to: "sections#ver_areas", as:"ver_areas"
  get 'borrar_area/:id_area,:id_section', to: "sections#borrar_area", as: "borrar_area"
  
  #rutas presupuestos para reparto
  get "/nuevo_pres_reparto", to: "budget_distributions#nuevo_pres_reparto", as:"nuevo_pres_reparto"
  post "/crear_presupuesto_reparto", to: "budget_distributions#crear_presupuesto_reparto", as:"crear_presupuesto_reparto"
  get 'formulario_agregar_detalle_reparto', to: "budget_distributions#formulario_agregar_detalle_reparto", as: "formulario_agregar_detalle_reparto"
  post "/guardar_detalle_reparto", to: "budget_distributions#guardar_detalle_reparto", as:"guardar_detalle_reparto"
  get 'eliminar_partida_reparto/:id_partida', to:"budget_distributions#eliminar_partida_reparto", as: "eliminar_partida_reparto"
  get 'budget_distributions/:id/imprimir', to: "budget_distributions#show", as: "presupuesto_imprimir"
  get 'solicitar_presupuesto_reparto/:id', to: "budget_distributions#solicitar_presupuesto_reparto", as: "solicitar_presupuesto_reparto"
  get 'borrar_presupuesto_reparto/:id',to: "budget_distributions#borrar_presupuesto_reparto", as: "borrar_presupuesto_reparto"
  
  #rutas presupuestos para administracion
  get "/nuevo_presupuesto_admin", to: "budget_administrations#nuevo_presupuesto_admin", as:"nuevo_presupuesto_admin"
  post "/crear_presupuesto_admin", to: "budget_administrations#crear_presupuesto_admin", as:"crear_presupuesto_admin"
  get 'solicitar_presupuesto_admin/:id', to: "budget_administrations#solicitar_presupuesto_admin", as: "solicitar_presupuesto_admin"
  get 'borrar_presupuesto_admin/:id',to: "budget_administrations#borrar_presupuesto_admin", as: "borrar_presupuesto_admin"
  
  #cargar factura 
  get 'documentos_factura/:id_consumo', to: "consumptions#documentos_factura", as: "documentos_factura"
  post 'cargar_factura', to: "consumptions#cargar_factura", as: "cargar_factura"
  get 'cancelar_encabezado/:folio', to: "consumptions#cancelar_encabezado", as: "cancelar_encabezado"
  get 'documentos_pdf/:id_consumo', to: "consumptions#documentos_pdf", as: "documentos_pdf"
  post 'cargar_pdf', to: "consumptions#cargar_pdf", as: "cargar_pdf"
  post 'solicitar_autorizacion/:folio', to: "consumptions#solicitar_autorizacion", as: "solicitar_autorizacion"
  post 'solicitar_autorizacion8/:folio', to: "consumptions#solicitar_autorizacion8", as: "solicitar_autorizacion8"
  post 'solicitar_autorizacion16/:folio', to: "consumptions#solicitar_autorizacion16", as: "solicitar_autorizacion16"
  get 'borrar_carga/:id',to: "consumptions#borrar_carga", as: "borrar_carga"

app/helpers/workshop_certifications_helper.rb
module WorkshopCertificationsHelper
end

app/views/workshop_certifications/_caratulas.html.erb
<div class="row">
    <% @documentos.each do |doc| %>
        <div class="col-lg-4">
            <div class="card bg-light" style="max-width: 100%; ">
                <div class="card-body">
                    <center>
                        <% if doc.caratulas.attached? and doc.caratulas.content_type == "application/pdf" %>
                            <embed src="<%= url_for(doc.caratulas) %>" type="application/pdf" style="max-width: 100%; max-height:100px;" />
                            <br><br>
                            <%= link_to "Descargar", rails_blob_path(doc.caratulas, disposition: 'attachment'), class: "btn btn-primary m-btn m-btn--custom" %>
                            <br><br>
                            <%#if doc.expenses_trips_expense.expenses_trip.status != "En comprobación" and doc.expenses_trips_expense.expenses_trip.status != "En revisión"%>
                                <%#= link_to "Eliminar", eliminar_documento_path(doc.id), class: "btn btn-danger m-btn m-btn--custom", data: {confirm: "¿Desea eliminar este documento?"}, remote: true %>
                            <%#end%>
                        <% elsif doc.caratulas.attached? and (doc.caratulas.content_type == "image/png" or doc.caratulas.content_type == "image/jpg" or doc.caratulas.content_type == "image/jpeg" or doc.caratulas.content_type == "image/gif") %>
                            <%= image_tag doc.caratulas, style: "max-height:100px; max-width:100%;" %>
                            <br><br>
                            <%= link_to "Descargar", rails_blob_path(doc.caratulas, disposition: 'attachment'), class: "btn btn-primary m-btn m-btn--custom" %>
                            <br><br>
                            <%#if doc.expenses_trips_expense.expenses_trip.status != "En comprobación" and doc.expenses_trips_expense.expenses_trip.status != "En revisión"%>
                                <%#= link_to "Eliminar", eliminar_documento_path(doc.id), class: "btn btn-danger m-btn m-btn--custom", data: {confirm: "¿Desea eliminar este documento?"}, remote: true %>
                            <%#end%>
                        <% elsif doc.caratulas.attached? %>
                            <h6><%= doc.caratulas.filename %></h6>
                            <br>
                            <%= link_to "Descargar", rails_blob_path(doc.caratulas, disposition: 'attachment'), class: "btn btn-primary m-btn m-btn--custom" %>
                            <br><br>
                            <%#if doc.expenses_trips_expense.expenses_trip.status != "En comprobación" and doc.expenses_trips_expense.expenses_trip.status != "En revisión"%>
                                <%#= link_to "Eliminar", eliminar_documento_path(doc.id), class: "btn btn-danger m-btn m-btn--custom", data: {confirm: "¿Desea eliminar este documento?"}, remote: true %>
                            <%#end%>
                        <% end %>  
                    </center>                  
                    <div class="row">                        
                        <div class="float-right">
                            <%#= link_to 'Editar', editar_reembolso_path(card.id), :class => "btn btn-primary m-btn m-btn--custom", style:'text-decoration:none' %>
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
    <% end %>
</div>    

app/views/workshop_certifications/comprobante_taller.js.erb
$("#contenido").html("<%= escape_javascript(render partial: 'comprobante_taller') %>");
$("#titulo_modal_general").text("Agregar documentos a concepto");
$(".modal_general").modal("show")

app/views/workshop_certifications/constancia_taller.js.erb
$("#contenido").html("<%= escape_javascript(render partial: 'constancia_taller') %>");
$("#titulo_modal_general").text("Agregar documentos a concepto");
$(".modal_general").modal("show")

app/views/workshop_certifications/crear_ticket_taller.html.erb
<br>
<div class="container">
    <div class="card card-custom gutter-b">
        <div class="row">
            <div class="col-lg-12">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-label float-left">Registrar taller</h3>
                        <%= link_to 'Regresar', workshop_certifications_path, class: "btn btn-default float-right" %>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <%= form_for('', url: guardar_ticket_taller_path,method: :post, remote: true,authenticity_token: true) do |form|%>
                <div class="card-body">
                    <div class="float-right">
                        <%= submit_tag "Guardar", class: "btn btn-success", style:"background-color: #2dbe06 !important;"%>
                    </div> <br><br>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" style="font-family: Arial; font-size:15px;">Clave taller:</label>
                        <div class="col-sm-0">
                            <%= form.text_field :clave, class: "form-control", style:"width: 250px !important;" %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" style="font-family: Arial; font-size:14px;">Empresa*</label>
                        <div class="col-sm-0">
                        <%= collection_select('', :catalog_company_id, CatalogCompany.listado_empresas,:id, :nombre, {prompt:"Escribe el nombre de la empresa"}, {:class => " form-control m-input m-input--air uneditable-input chosen-select"})%>
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" style="font-family: Arial; font-size:15px;">CEDIS*</label>
                        <div class="col-sm-0">
                        <%= collection_select('',:catalog_branch_id ,CatalogBranch.listado_cedis, :id, :decripcion, {prompt:"Seleccione el cedis"}, {:class => " form-control m-input m-input--air uneditable-input chosen-select"})%>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" style="font-family: Arial; font-size:15px;">Razón Social:</label>
                        <div class="col-sm-0">
                        <%= form.text_field :razonsocial, class: "form-control", style:"width: 250px !important;",required:true %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" style="font-family: Arial; font-size:15px;">Nombre taller:</label>
                        <div class="col-sm-0">
                        <%= form.text_field :nombre_taller, class: "form-control", style:"width: 250px !important;",required:true %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" style="font-family: Arial; font-size:15px;">Especialidad:</label>
                        <div class="col-sm-0">
                        <%= form.text_field :especialidad, class: "form-control", style:"width: 250px !important;" %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" style="font-family: Arial; font-size:15px;">Responsable:</label>
                        <div class="col-sm-0">
                        <%= form.text_field :responsable, class: "form-control", style:"width: 250px !important;" %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" style="font-family: Arial; font-size:15px;"> Teléfono:</label>
                        <div class="col-sm-0">
                        <%= form.text_field :telefono, class: "form-control", style:"width: 250px !important;" %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" style="font-family: Arial; font-size:15px;">Domicilio:</label>
                        <div class="col-sm-0">
                        <%= form.text_area :domicilio, class: "form-control", style:"width: 250px !important;" %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" style="font-family: Arial; font-size:15px;">Correo electrónico:</label>
                        <div class="col-sm-0">
                        <%= form.text_field :correo, class: "form-control", style:"width: 250px !important;" %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" style="font-family: Arial; font-size:15px;">Condición de pago:</label>
                        <div class="col-sm-0">
                        <%= form.text_field :condicion, class: "form-control", style:"width: 250px !important;", required:true %>
                        </div>
                    </div>
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label" style="font-family: Arial; font-size:15px;">Fecha de certificación:</label>
                            <div class="col-sm-0">
                            <div class="input-group date" id="datetimepicker7" data-target-input="nearest" data-date-format="DD/MM/YYYY">
                                <%= form.text_field :fecha, class: "form-control datetimepicker-input",style:"width: 210px !important;", required:true %>
                                <div class="input-group-append" data-target="#datetimepicker7" data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
            <% end %>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
    $("#catalog_company_id").change(function(){
    var empresa = $(this).val();
    $.ajax({
    type: "POST",
    url: "<%= cedis_x_empresa_taller_path %>",
    data: {empresa: empresa, authenticity_token: $('meta[name=csrf-token]').attr('content')}
    })
    })
    })
  </script>

app/views/workshop_certifications/index.html.erb
<br>
<div class="container">
  <div class="card card-custom gutter-b">
  <div class="card-header">
    <div class="card-title">
      <h3 class="card-label">Certificación de talleres</h3>
    </div>
    <div class="float-right">
      <br>
      <!-- <%= link_to 'Nuevo', crear_ticket_taller_path,class:"btn btn-primary font-weight-bolder",style:"border-radius: 0.42rem;", data: { turbolinks: false } %> -->

    </div>
  </div>
  <div class="card-body">
    <div class="container">
      <%= form_tag workshop_certifications_path, :method => :get do %>
             <div class="row">
                 <div class="col">
                     <label class="col-sm-0 col-form-label" style="font-family: Arial; font-size:15px;">No. Ticket: </label>
                     <%= text_field_tag :numero, params[:numero], class:"form-control" %>
                 </div>
                 <div class="col">
                     <label class="col-sm-0 col-form-label" style="font-family: Arial; font-size:15px;">Fecha inicio:</label>
                      <div class="input-group date" id="datetimepicker7" data-target-input="nearest" data-date-format="DD/MM/YYYY">
                        <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker7" name="start_date" id="start_date">
                        <div class="input-group-append" data-target="#datetimepicker7" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                      </div>                 
                  </div>
                  <div class="col">
                    <label class="col-sm-0 col-form-label" style="font-family: Arial; font-size:15px;">Fecha fin:</label>
                     <div class="input-group date" id="datetimepicker8" data-target-input="nearest" data-date-format="DD/MM/YYYY">
                       <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker8" name="end_date" id="end_date">
                       <div class="input-group-append" data-target="#datetimepicker8" data-toggle="datetimepicker">
                           <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                       </div>
                     </div>                 
                 </div>
                 <div class="col">
                  <label class="col-sm-0 col-form-label" style="font-family: Arial; font-size:15px;">Estatus:</label>
                  <select name="status" id="status"  class= "form form-group form-control">
                    <option value=""></option>
                    <option value="0">Pendiente de documentación</option>
                    <option value="1">Pendiente de revisión</option>
                    <option value="2">Autorizado</option>
                    <option value="3">Rechazado</option>
                  </select>
                 </div>
                 <div class="col">
                   <br><br>
                   <%= submit_tag "Buscar", class:"btn btn-primary" %>
                 <% end %>
               </div>
             </div>   
    </div>
    <div class="table-responsive">
        <table  class="table table-bordered table-striped table-sm text-center">
          <thead>
            <tr>
              <th>No. Ticket</th>
              <th>Taller</th>
              <th>Especialidad</th>
              <th>Domicilio</th>
              <th>Contacto</th>
              <th>Teléfono</th>
              <th>Email</th>
              <th>Fecha ticket</th>
              <th>Condición de pago</th>
              <th>Estatus</th>
              <th colspan="2">Acciones</th>
              <th colspan="5">Expendiente</th>
            </tr>
          </thead>

          <tbody>
            <% @workshop_certifications.each do |workshop_certification| %>
              <tr>
                <td><%= workshop_certification.numero_ticket %></td>
                <td><%= workshop_certification.catalog_workshop.nombre_taller %></td>
                <td><%= workshop_certification.catalog_workshop.especialidad %></td>
                <td><%= workshop_certification.catalog_workshop.domicilio %></td>
                <td><%= workshop_certification.catalog_workshop.responsable %></td>
                <td style="width: 7%"><%= workshop_certification.catalog_workshop.telefono %></td>
                <td><%= workshop_certification.catalog_workshop.correo %></td>
                <td style="width: 8%;"><%= workshop_certification.fecha.strftime('%d/%m/%y') %></td>
                <td><%= workshop_certification.condiciones %></td>
                <td><%= workshop_certification.estatus %></td>
                <td>
                  <div class="dropdown dropdown-inline">
                      <%= link_to workshop_certification, title: "Ver detalle" do %>
                      <span class='fas fa-eye' style='font-size:16px;color:#A6ACAF'></span>
                      </span>
                      <% end %>
                  </div>
                </td>
                <% if can? :edit, WorkshopCertification %>
                <% if workshop_certification.estatus != "Pendiente de revisión" and workshop_certification.estatus != "Autorizado" %>
                <td>
                  <div class="dropdown dropdown-inline">
                    <%= link_to edit_workshop_certification_path(workshop_certification.id), title: "Editar" do %>
                    <span class="svg-icon svg-icon-md"> 
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px"
                    viewBox="0 0 24 24" version="1.1">
                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                    <rect x="0" y="0" width="24" height="24"></rect>
                    <path d="M8,17.9148182 L8,5.96685884 C8,5.56391781 8.16211443,5.17792052 8.44982609,4.89581508 L10.965708,2.42895648 C11.5426798,1.86322723 12.4640974,1.85620921 13.0496196,2.41308426 L15.5337377,4.77566479 C15.8314604,5.0588212 16,5.45170806 16,5.86258077 L16,17.9148182 C16,18.7432453 15.3284271,19.4148182 14.5,19.4148182 L9.5,19.4148182 C8.67157288,19.4148182 8,18.7432453 8,17.9148182 Z"
                    fill="#000000" fill-rule="nonzero" transform="translate(12.000000, 10.707409) rotate(-135.000000) translate(-12.000000, -10.707409) ">
                    </path>
                    <rect fill="#000000" opacity="0.3" x="5" y="20" width="15" height="2" rx="1"></rect>
                    </g>
                    </svg> 
                    </span>
                    <% end %>
                    </div>  
                </td>
                <% end %>                 
                <% end %>
                <% if can? :fotos_taller, WorkshopCertification %>
                  <% if workshop_certification.estatus != "Pendiente de revisión" %>
                    <td>
                      <div class="dropdown dropdown-inline">
                          <%= link_to fotos_taller_path(workshop_certification.id),remote: true, title:"Adjuntar fotografías" do%>
                              <span class='far fa-file-image' style='font-size:16px;color:#A6ACAF'></span>
                              </span>
                          <% end %>
                      </div>
                    </td>
                    <td>
                      <div class="dropdown dropdown-inline">
                          <%= link_to comprobante_taller_path(workshop_certification.id),remote: true, title:"Adjuntar comprobante de domicilio" do%>
                              <span class='far fa-address-card' style='font-size:16px;color:#A6ACAF'></span>
                              </span>
                          <% end %>
                      </div>
                    </td>
                    <td>
                      <div class="dropdown dropdown-inline">
                        <%= link_to caratulas_taller_path(workshop_certification.id),remote: true, title:"Adjuntar caratulas de estado de cuenta" do%>
                          <span class='fas fa-file-invoice-dollar' style='font-size:16px;color:#A6ACAF'></span>
                          </span>
                        <% end %>
                      </div>
                    </td>
                    <td>
                      <div class="dropdown dropdown-inline">
                        <%= link_to constancia_taller_path(workshop_certification.id),remote: true, title:"Adjuntar constancia de situación fiscal" do%>
                          <span class='far fa-file-alt' style='font-size:16px;color:#A6ACAF'></span>
                          </span>
                        <% end %>
                      </div>
                    </td>
                    <td>
                      <div class="dropdown dropdown-inline">
                        <%= link_to rfc_taller_path(workshop_certification.id),remote: true, title:"Adjuntar RFC" do%>
                          <span class='fas fa-tools' style='font-size:16px;color:#A6ACAF'></span>
                          </span>
                        <% end %>
                      </div>
                    </td>
                  <% end %>
                <% end %>
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
    </div>
</div>
<script type="text/javascript">
  $(function () {
    $('#datetimepicker7').datetimepicker({
    format: 'DD/MM/YYYY',
    locale: 'es'
    });
    $('#datetimepicker8').datetimepicker({
    format: 'DD/MM/YYYY',
    locale: 'es',
    useCurrent: false
    });
    
    $("#datetimepicker7").on("change.datetimepicker", function (e) {
        $('#datetimepicker8').datetimepicker('minDate', e.date);
    });
    $("#datetimepicker8").on("change.datetimepicker", function (e) {
        $('#datetimepicker7').datetimepicker('maxDate', e.date);
    });
});
</script>

app/views/workshop_certifications/new.html.erb
<h1>New Workshop Certification</h1>

<%= render 'form', workshop_certification: @workshop_certification %>

<%= link_to 'Back', workshop_certifications_path %>