config/routes.rb
Rails.application.routes.draw do
  resources :insurance_policies
  resources :valuations
  resources :jde_logs
  resources :deadlines
  resources :vehicle_logs
  resources :vehicle_items
  resources :concept_services
  resources :questions
  resources :answers
  resources :catalog_tires_batteries
  resources :ticket_tire_batteries
  resources :parameters
  resources :sections
  get 'budgets/index'
  resources :maintenance_tickets
  resources :maintenance_frecuencies
  resources :agency_mileage_indicators
  resources :workshop_certifications
  resources :review_workshops
  get 'catalog_branches_users/index'
  resources :service_orders
  resources :maintenance_programs
  resources :maintenance_appointments
  resources :mileage_indicators
  resources :maintenance_logs
  resources :mechanical_reviews
  resources :catalog_considerations
  resources :expense_vehicle_types
  resources :tuning_prices
  resources :monthly_yields
  resources :maintenance_controls
  resources :insurance_report_tickets
  resources :catalog_workshops
  resources :consumptions
  resources :accumulated_fuels
  resources :vehicle_consumptions
  resources :budget_administrations
  resources :budget_delivery_replacements
  resources :budget_sales_replacements
  resources :delivery_addresses
  resources :deliveries
  resources :customers
  resources :budget_distributions
  resources :reasons
  resources :purchase_orders
  resources :perform_targets
  resources :accounting_impacts
  resources :competition_tables
  resources :vehicle_indicators
  get 'users', to: "users#index", as: "users"
  post "/create_new_user", to: "users#create_new_user", as: "create_new_user"
  patch "/update", to: "users#update", as: "update"
  # get 'users/destroy'
  
  resources :user_vehicles
  devise_for :users
  resources :type_sinisters
  resources :catalog_responsives
  resources :catalogo_adaptations
  resources :catalog_areas
  resources :fuel_budgets
  resources :vehicle_prices
  resources :vehicle_permits
  
  resources :vehicle_models
  resources :vehicle_checklists
  resources :catalog_branches
  resources :catalog_models
  resources :catalog_brands
  resources :catalog_roles
  resources :catalog_licences
  resources :catalog_personals
  resources :catalog_vendors
  resources :vehicles
  resources :cost_centers
  resources :insurance_beneficiaries
  resources :policy_coverages
  resources :billed_companies
  resources :responsables
  resources :catalog_repairs
  resources :vehicle_statuses
  resources :vehicle_types
  resources :plate_states
  resources :catalog_routes
  resources :budget_concepts
  resources :order_service_types
  resources :vehicle_brands
  resources :branch_offices
  resources :catalog_companies
  resources :movil_api
  resources :warehouses
  #expediente
  post 'uploads/:id', to: "vehicles#uploads",as: "uploads"
  get 'ver_documentos/:id', to: "vehicles#ver_documentos",as: "ver_documentos"
  get 'document_detail/:file_id', to: "vehicles#document_detail",as: "document_detail"

  get 'borrar_firma/:id',to: "parameters#borrar_firma", as: "borrar_firma"
  post 'img_ticket_taller',to: "movil_api#img_ticket_taller"
  get 'ver_ticket_taller/:maintenance_ticket_id',to: "movil_api#ver_ticket_taller"
  post 'bimonthly_img', to: "movil_api#bimonthly_img"
  get 'ver_biomonthly_img/:bimonthly_verification_id', to: "movil_api#bimonthly_img"
  post 'cargar_imagen_licencia', to: "movil_api#cargar_imagen_licencia"
  post 'cargar_imagen_siniestro', to: "movil_api#cargar_imagen_siniestro"
  get 'ver_firma_usuario/:user_id', to: "movil_api#ver_firma_usuario"
  post 'firma_usuario', to: "movil_api#firma_usuario"
  get 'ver_licencias/:user_id', to: "movil_api#ver_licencias"
  get 'ver_evidencia_check/:checklist_response_id', to: "movil_api#ver_evidencia_check"
  
  

  put 'firma_venta/:vehicle_id', to: "movil_api#firma_venta"
  get 'ver_firma_venta/:vehicle_id', to: "movil_api#ver_firma_venta"
  post 'agregar_img_llantas', to: "movil_api#agregar_img_llantas"
  get 'ver_img_llantas/:ticket_tire_battery_id', to: "movil_api#ver_img_llantas"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: 'home#login'
  #Maestro de vehiculos
  root to: "vehicles#index"
  post '/import_vehicles', to: 'vehicles#import_vehicles', as: "import_vehicles"
  get '/template_download_vehicles', to: 'vehicles#template_download_vehicles', as: "template_download_vehicles"
  get 'generar_excel', to: "vehicles#generar_excel", as: "generar_excel"
  get 'cancelar_compra/:id',to: "vehicles#cancelar_compra", as: "cancelar_compra"
  get 'listado_checklist/:id',to: "vehicles#listado_checklist", as: "listado_checklist"
  get 'detalle_checklist/:checklist_id',to: "vehicles#detalle_checklist", as: "detalle_checklist"
  get 'detalle_auditoria/:auditoria_id',to: "vehicles#detalle_auditoria", as: "detalle_auditoria"
  get 'vehicle_expenses/:id',to: "vehicles#vehicle_expenses", as: "vehicle_expenses"
  post 'gastos_vehiculo_x_fecha/:id',to: "vehicles#gastos_vehiculo_x_fecha", as: "gastos_vehiculo_x_fecha"
  #orden de compra
  get 'purchase_orders/:id/imprimir', to: "purchase_orders#imprimir", as: "orden_imprimir"
  get 'documentos_orden/:id', to: "purchase_orders#documentos_orden", as: "documentos_orden"
  post 'cargar_documento_orden', to: "purchase_orders#cargar_documento_orden", as: "cargar_documento_orden"
  get 'factura_orden/:id', to: "purchase_orders#factura_orden", as: "factura_orden"
  post 'cargar_factura_orden', to: "purchase_orders#cargar_factura_orden", as: "cargar_factura_orden"
  post '/filtrado_ordenes', to: "purchase_orders#filtrado_ordenes", as: "filtrado_ordenes"
  get "/nueva_orden", to: "purchase_orders#nueva_orden", as:"nueva_orden"
  post "/crear_orden", to: "purchase_orders#crear_orden", as:"crear_orden"
  get 'formulario_agregar_detalle_orden', to: "purchase_orders#formulario_agregar_detalle_orden", as: "formulario_agregar_detalle_orden"
  post "/guardar_detalle_orden", to: "purchase_orders#guardar_detalle_orden", as:"guardar_detalle_orden"
  post '/guardar_total', to: "purchase_orders#guardar_total", as: "guardar_total"
  get 'eliminar_partida_orden/:id_partida', to:"purchase_orders#eliminar_partida_orden", as: "eliminar_partida_orden"
  get 'purchase_orders/:id/imprimir_orden', to: "purchase_orders#show", as: "imprimir_orden"
  
  #rutas presupuestos para venta
  get "/nuevo_presupuesto", to: "budget_concepts#nuevo_presupuesto", as:"nuevo_presupuesto"
  post "/crear_presupuesto", to: "budget_concepts#crear_presupuesto", as:"crear_presupuesto"
  get 'formulario_agregar_detalle', to: "budget_concepts#formulario_agregar_detalle", as: "formulario_agregar_detalle"
  post "/guardar_detalle", to: "budget_concepts#guardar_detalle", as:"guardar_detalle"
  get 'eliminar_partida/:id_partida', to:"budget_concepts#eliminar_partida", as: "eliminar_partida"
  get 'budget_concepts/:id/imprimir_pres', to: "budget_concepts#show", as: "presupuesto_pdf_imprimir"
  get 'solicitar_presupuesto_venta/:id', to: "budget_concepts#solicitar_presupuesto_venta", as: "solicitar_presupuesto_venta"
  get 'borrar_presupuesto_venta/:id',to: "budget_concepts#borrar_presupuesto_venta", as: "borrar_presupuesto_venta"
  
  # secciones- area
  get "/asignar_area/:id", to: "sections#asignar_area", as:"asignar_area"
  post "/guardar_area/:id", to: "sections#guardar_area", as:"guardar_area"
  get "/ver_areas/:id", to: "sections#ver_areas", as:"ver_areas"
  get 'borrar_area/:id_area,:id_section', to: "sections#borrar_area", as: "borrar_area"
  
  #rutas presupuestos para reparto
  get "/nuevo_pres_reparto", to: "budget_distributions#nuevo_pres_reparto", as:"nuevo_pres_reparto"
  post "/crear_presupuesto_reparto", to: "budget_distributions#crear_presupuesto_reparto", as:"crear_presupuesto_reparto"
  get 'formulario_agregar_detalle_reparto', to: "budget_distributions#formulario_agregar_detalle_reparto", as: "formulario_agregar_detalle_reparto"
  post "/guardar_detalle_reparto", to: "budget_distributions#guardar_detalle_reparto", as:"guardar_detalle_reparto"
  get 'eliminar_partida_reparto/:id_partida', to:"budget_distributions#eliminar_partida_reparto", as: "eliminar_partida_reparto"
  get 'budget_distributions/:id/imprimir', to: "budget_distributions#show", as: "presupuesto_imprimir"
  get 'solicitar_presupuesto_reparto/:id', to: "budget_distributions#solicitar_presupuesto_reparto", as: "solicitar_presupuesto_reparto"
  get 'borrar_presupuesto_reparto/:id',to: "budget_distributions#borrar_presupuesto_reparto", as: "borrar_presupuesto_reparto"
  
  #rutas presupuestos para administracion
  get "/nuevo_presupuesto_admin", to: "budget_administrations#nuevo_presupuesto_admin", as:"nuevo_presupuesto_admin"
  post "/crear_presupuesto_admin", to: "budget_administrations#crear_presupuesto_admin", as:"crear_presupuesto_admin"
  get 'solicitar_presupuesto_admin/:id', to: "budget_administrations#solicitar_presupuesto_admin", as: "solicitar_presupuesto_admin"
  get 'borrar_presupuesto_admin/:id',to: "budget_administrations#borrar_presupuesto_admin", as: "borrar_presupuesto_admin"
  
  #cargar factura 
  get 'documentos_factura/:id_consumo', to: "consumptions#documentos_factura", as: "documentos_factura"
  post 'cargar_factura', to: "consumptions#cargar_factura", as: "cargar_factura"
  get 'cancelar_encabezado/:folio', to: "consumptions#cancelar_encabezado", as: "cancelar_encabezado"
  get 'documentos_pdf/:id_consumo', to: "consumptions#documentos_pdf", as: "documentos_pdf"
  post 'cargar_pdf', to: "consumptions#cargar_pdf", as: "cargar_pdf"
  post 'solicitar_autorizacion/:folio', to: "consumptions#solicitar_autorizacion", as: "solicitar_autorizacion"
  post 'solicitar_autorizacion8/:folio', to: "consumptions#solicitar_autorizacion8", as: "solicitar_autorizacion8"
  post 'solicitar_autorizacion16/:folio', to: "consumptions#solicitar_autorizacion16", as: "solicitar_autorizacion16"
  get 'borrar_carga/:id',to: "consumptions#borrar_carga", as: "borrar_carga"

app/models/fuel_budget.rb
class FuelBudget < ApplicationRecord
    include ActionView::Helpers::NumberHelper
    validates :precio_litro, presence: true
    belongs_to :vehicle

    after_create :vehicle_log_create

    def vehicle_log_create
        VehicleLog.create(texto: "El usuario #{User.current_user.name} #{User.current_user.last_name} registró un nuevo presupuesto de combustible al vehículo con número económico #{self.vehicle.numero_economico} de #{self.litros} litros y #{number_to_currency(self.precio_litro)} por litro.", vehicle_id: self.vehicle_id, user_id: User.current_user.id)
    end
end

app/controllers/fuel_budgets_controller.rb
class FuelBudgetsController < ApplicationController
  before_action :set_fuel_budget, only: [:show, :edit, :update, :destroy]
  before_action :validacion_menu
  # GET /fuel_budgets
  # GET /fuel_budgets.json
  def index
    @fuel_budgets = FuelBudget.all
  end

  # GET /fuel_budgets/1
  # GET /fuel_budgets/1.json
  def show
  end

  # GET /fuel_budgets/new
  def new
    @fuel_budget = FuelBudget.new
  end

  # GET /fuel_budgets/1/edit
  def edit
  end

  # POST /fuel_budgets
  # POST /fuel_budgets.json
  def create
    begin
      @fuel_budget = FuelBudget.new(fuel_budget_params)
  
      respond_to do |format|
        if @fuel_budget.save
          format.html { redirect_to fuel_budgets_path, notice: 'Fuel budget was successfully created.' }
          format.json { render :show, status: :created, location: @fuel_budget }
        else
          format.html { render :new }
          format.json { render json: @fuel_budget.errors, status: :unprocessable_entity }
        end
      end
    rescue => exception
      redirect_to fuel_budgets_path
      flash[:alert] = "Ocurrio un error, favor de contactar soporte. Error: #{exception}"
    end
  end

  # PATCH/PUT /fuel_budgets/1
  # PATCH/PUT /fuel_budgets/1.json
  def update
    begin
      respond_to do |format|
        if @fuel_budget.update(fuel_budget_params)
          format.html { redirect_to fuel_budgets_path, notice: 'Fuel budget was successfully updated.' }
          format.json { render :show, status: :ok, location: @fuel_budget }
        else
          format.html { render :edit }
          format.json { render json: @fuel_budget.errors, status: :unprocessable_entity }
        end
      end
    rescue => exception
      redirect_to fuel_budgets_path
      flash[:alert] = "Ocurrio un error, favor de contactar soporte. Error: #{exception}"
    end
  end

  # DELETE /fuel_budgets/1
  # DELETE /fuel_budgets/1.json
  def destroy
    @fuel_budget.destroy
    respond_to do |format|
      format.html { redirect_to fuel_budgets_url, notice: 'Fuel budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def validacion_menu
      session["menu1"] = "Seguridad"
      session["menu2"] = "Catálogos"
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_fuel_budget
      @fuel_budget = FuelBudget.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fuel_budget_params
      params.require(:fuel_budget).permit(:litros, :precio_litro,:vehicle_id,:formula_presupuesto)
    end
end

app/helpers/fuel_budgets_helper.rb
module FuelBudgetsHelper
end

app/views/fuel_budgets/_form.html.erb
<%= form_with(model: fuel_budget, local: true) do |form| %>
  <% if fuel_budget.errors.any? %>
  <div class="alert alert-danger">Error al registrar:
    <div id="error_explanation">
      <ul>
        <% fuel_budget.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    </div>
  <% end %>
  <div class="float-right">
    <%= form.submit "Guardar", class: "btn btn-success", style:"background-color: #2dbe06 !important;" %>
   </div>
  <br><br>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label" style="font-family: Arial; font-size:15px;">No. Económico*</label>
    <div class="col-sm-0">
      <%= collection_select(:fuel_budget,:vehicle_id ,Vehicle.listado_vehiculos, :id, :numero_economico, {prompt:"Vehículo"}, {:class => " form-control m-input m-input--air uneditable-input chosen-select"})%>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label" style="font-family: Arial; font-size:15px;">Litros:</label>
    <div class="col-sm-0">
      <%= form.number_field :litros, step: :any,class: "form-control", style:"width: 250px !important;"%>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label" style="font-family: Arial; font-size:15px;">Precio Litro:</label>
    <div class="col-sm-0">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text">$</span>
        </div>
        <%= form.number_field :precio_litro, step: :any,class: "form-control", style:"width: 220px !important;" %>
      </div>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label" style="font-family: Arial; font-size:15px;">Fórmula presupuesto</label>
    <div class="col-sm-0">
      <%= form.text_field :formula_presupuesto,class: "form-control", style:"width: 250px !important;" %>
    </div>
  </div>
<% end %>

app/views/fuel_budgets/edit.html.erb
<br>
<div class="container">
    <div class="card card-custom gutter-b">
        <div class="row">
            <div class="col-lg-12">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-label float-left">Editar presupuesto de combustible</h3>
                        <%= link_to 'Regresar', fuel_budgets_path, class: "btn btn-default float-right" %>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <%= render 'form', fuel_budget: @fuel_budget %>
        </div>
    </div>
</div>

app/views/fuel_budgets/index.html.erb
<br>
<div class="container">
  <div class="card card-custom gutter-b">
  <div class="card-header">
    <div class="card-title">
      <h3 class="card-label">Presupuesto de combustible
      <span class="text-muted pt-2 font-size-sm d-block">Catálogo de parámetro presupuesto combustible</span>
      </h3>
    </div>
    <div class="float-right">
      <br>
      <%= link_to 'Nuevo', new_fuel_budget_path,class:"btn btn-primary font-weight-bolder",style:"border-radius: 0.42rem;", data: { turbolinks: false } %>
    </div>
  </div>
  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th>No. Económico</th>
          <th>Litros</th>
          <th>Precio litro</th>
          <th>Fórmula presupuesto</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @fuel_budgets.each do |fuel_budget| %>
          <tr>
            <td><%= fuel_budget.vehicle.numero_economico %></td>
            <td><%= fuel_budget.litros%></td>
            <td>$<%= fuel_budget.precio_litro %></td>
            <td><%= fuel_budget.formula_presupuesto%></td>
            <td>
              <div class="dropdown dropdown-inline">
                <%= link_to edit_fuel_budget_path(fuel_budget), title: "Editar" do %>
                <span class="svg-icon svg-icon-md"> 
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px"
                viewBox="0 0 24 24" version="1.1">
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                <rect x="0" y="0" width="24" height="24"></rect>
                <path d="M8,17.9148182 L8,5.96685884 C8,5.56391781 8.16211443,5.17792052 8.44982609,4.89581508 L10.965708,2.42895648 C11.5426798,1.86322723 12.4640974,1.85620921 13.0496196,2.41308426 L15.5337377,4.77566479 C15.8314604,5.0588212 16,5.45170806 16,5.86258077 L16,17.9148182 C16,18.7432453 15.3284271,19.4148182 14.5,19.4148182 L9.5,19.4148182 C8.67157288,19.4148182 8,18.7432453 8,17.9148182 Z"
                fill="#000000" fill-rule="nonzero" transform="translate(12.000000, 10.707409) rotate(-135.000000) translate(-12.000000, -10.707409) ">
                </path>
                <rect fill="#000000" opacity="0.3" x="5" y="20" width="15" height="2" rx="1"></rect>
                </g>
                </svg> 
                </span>
                <% end %>
              </div>  
            </td>
            <td>
              <div class="dropdown dropdown-inline">
                <%= link_to fuel_budget, title:"Eliminar" ,method: :delete, data: { confirm: '¿Estas seguro?' } do %>
                <span class="svg-icon svg-icon-md"> <svg xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px"
                  viewBox="0 0 24 24" version="1.1">
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <rect x="0" y="0" width="24" height="24"></rect>
                  <path d="M6,8 L6,20.5 C6,21.3284271 6.67157288,22 7.5,22 L16.5,22 C17.3284271,22 18,21.3284271 18,20.5 L18,8 L6,8 Z"
                  fill="#000000" fill-rule="nonzero"></path>
                  <path d="M14,4.5 L14,4 C14,3.44771525 13.5522847,3 13,3 L11,3 C10.4477153,3 10,3.44771525 10,4 L10,4.5 L5.5,4.5 C5.22385763,4.5 5,4.72385763 5,5 L5,5.5 C5,5.77614237 5.22385763,6 5.5,6 L18.5,6 C18.7761424,6 19,5.77614237 19,5.5 L19,5 C19,4.72385763 18.7761424,4.5 18.5,4.5 L14,4.5 Z"
                  fill="#000000" opacity="0.3"></path>
                  </g>
                  </svg> </span>
                <% end %>
                </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>

app/views/fuel_budgets/new.html.erb
<br>
<div class="container">
    <div class="card card-custom gutter-b">
        <div class="row">
            <div class="col-lg-12">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-label float-left">Nuevo presupuesto de combustible</h3>
                        <%= link_to 'Regresar' ,fuel_budgets_path , class: "btn btn-default float-right" %>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <%= render 'form', fuel_budget: @fuel_budget %>
        </div>
    </div>
</div>

app/views/fuel_budgets/show.html.erb
<br><br>
<div class="container">
  <div class="card card-custom gutter-b">
      <div class="row">
         <div class="col-lg-12">
            <div class="card-header">
              <div class="card-title">
                <h3 class="card-label float-left ">Presupuesto de combustible</h3>
                  <%= link_to 'Regresar', fuel_budgets_path, class:"btn btn-default float-right" %>
                </div>
             </div>
         </div>
      </div>
    <div class="card-body">
      <p>
        <strong>Descripcion:</strong>
        <%= @fuel_budget.descripcion %>
      </p>

      <p>
        <strong>Precio litro:</strong>
        <%= @fuel_budget.precio_litro %>
      </p>
      <%= link_to 'Editar', edit_fuel_budget_path(@fuel_budget), class:"btn btn-default" %>
    </div>
  </div>
</div>