config/routes.rb
Rails.application.routes.draw do
  resources :insurance_policies
  resources :valuations
  resources :jde_logs
  resources :deadlines
  resources :vehicle_logs
  resources :vehicle_items
  resources :concept_services
  resources :questions
  resources :answers
  resources :catalog_tires_batteries
  resources :ticket_tire_batteries
  resources :parameters
  resources :sections
  get 'budgets/index'
  resources :maintenance_tickets
  resources :maintenance_frecuencies
  resources :agency_mileage_indicators
  resources :workshop_certifications
  resources :review_workshops
  get 'catalog_branches_users/index'
  resources :service_orders
  resources :maintenance_programs
  resources :maintenance_appointments
  resources :mileage_indicators
  resources :maintenance_logs
  resources :mechanical_reviews
  resources :catalog_considerations
  resources :expense_vehicle_types
  resources :tuning_prices
  resources :monthly_yields
  resources :maintenance_controls
  resources :insurance_report_tickets
  resources :catalog_workshops
  resources :consumptions
  resources :accumulated_fuels
  resources :vehicle_consumptions
  resources :budget_administrations
  resources :budget_delivery_replacements
  resources :budget_sales_replacements
  resources :delivery_addresses
  resources :deliveries
  resources :customers
  resources :budget_distributions
  resources :reasons
  resources :purchase_orders
  resources :perform_targets
  resources :accounting_impacts
  resources :competition_tables
  resources :vehicle_indicators
  get 'users', to: "users#index", as: "users"
  post "/create_new_user", to: "users#create_new_user", as: "create_new_user"
  patch "/update", to: "users#update", as: "update"
  # get 'users/destroy'
  
  resources :user_vehicles
  devise_for :users
  resources :type_sinisters
  resources :catalog_responsives
  resources :catalogo_adaptations
  resources :catalog_areas
  resources :fuel_budgets
  resources :vehicle_prices
  resources :vehicle_permits
  
  resources :vehicle_models
  resources :vehicle_checklists
  resources :catalog_branches
  resources :catalog_models
  resources :catalog_brands
  resources :catalog_roles
  resources :catalog_licences
  resources :catalog_personals
  resources :catalog_vendors
  resources :vehicles
  resources :cost_centers
  resources :insurance_beneficiaries
  resources :policy_coverages
  resources :billed_companies
  resources :responsables
  resources :catalog_repairs
  resources :vehicle_statuses
  resources :vehicle_types
  resources :plate_states
  resources :catalog_routes
  resources :budget_concepts
  resources :order_service_types
  resources :vehicle_brands
  resources :branch_offices
  resources :catalog_companies
  resources :movil_api
  resources :warehouses
  #expediente
  post 'uploads/:id', to: "vehicles#uploads",as: "uploads"
  get 'ver_documentos/:id', to: "vehicles#ver_documentos",as: "ver_documentos"
  get 'document_detail/:file_id', to: "vehicles#document_detail",as: "document_detail"

  get 'borrar_firma/:id',to: "parameters#borrar_firma", as: "borrar_firma"
  post 'img_ticket_taller',to: "movil_api#img_ticket_taller"
  get 'ver_ticket_taller/:maintenance_ticket_id',to: "movil_api#ver_ticket_taller"
  post 'bimonthly_img', to: "movil_api#bimonthly_img"
  get 'ver_biomonthly_img/:bimonthly_verification_id', to: "movil_api#bimonthly_img"
  post 'cargar_imagen_licencia', to: "movil_api#cargar_imagen_licencia"
  post 'cargar_imagen_siniestro', to: "movil_api#cargar_imagen_siniestro"
  get 'ver_firma_usuario/:user_id', to: "movil_api#ver_firma_usuario"
  post 'firma_usuario', to: "movil_api#firma_usuario"
  get 'ver_licencias/:user_id', to: "movil_api#ver_licencias"
  get 'ver_evidencia_check/:checklist_response_id', to: "movil_api#ver_evidencia_check"
  
  

  put 'firma_venta/:vehicle_id', to: "movil_api#firma_venta"
  get 'ver_firma_venta/:vehicle_id', to: "movil_api#ver_firma_venta"
  post 'agregar_img_llantas', to: "movil_api#agregar_img_llantas"
  get 'ver_img_llantas/:ticket_tire_battery_id', to: "movil_api#ver_img_llantas"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: 'home#login'
  #Maestro de vehiculos
  root to: "vehicles#index"
  post '/import_vehicles', to: 'vehicles#import_vehicles', as: "import_vehicles"
  get '/template_download_vehicles', to: 'vehicles#template_download_vehicles', as: "template_download_vehicles"
  get 'generar_excel', to: "vehicles#generar_excel", as: "generar_excel"
  get 'cancelar_compra/:id',to: "vehicles#cancelar_compra", as: "cancelar_compra"
  get 'listado_checklist/:id',to: "vehicles#listado_checklist", as: "listado_checklist"
  get 'detalle_checklist/:checklist_id',to: "vehicles#detalle_checklist", as: "detalle_checklist"
  get 'detalle_auditoria/:auditoria_id',to: "vehicles#detalle_auditoria", as: "detalle_auditoria"
  get 'vehicle_expenses/:id',to: "vehicles#vehicle_expenses", as: "vehicle_expenses"
  post 'gastos_vehiculo_x_fecha/:id',to: "vehicles#gastos_vehiculo_x_fecha", as: "gastos_vehiculo_x_fecha"
  #orden de compra
  get 'purchase_orders/:id/imprimir', to: "purchase_orders#imprimir", as: "orden_imprimir"
  get 'documentos_orden/:id', to: "purchase_orders#documentos_orden", as: "documentos_orden"
  post 'cargar_documento_orden', to: "purchase_orders#cargar_documento_orden", as: "cargar_documento_orden"
  get 'factura_orden/:id', to: "purchase_orders#factura_orden", as: "factura_orden"
  post 'cargar_factura_orden', to: "purchase_orders#cargar_factura_orden", as: "cargar_factura_orden"
  post '/filtrado_ordenes', to: "purchase_orders#filtrado_ordenes", as: "filtrado_ordenes"
  get "/nueva_orden", to: "purchase_orders#nueva_orden", as:"nueva_orden"
  post "/crear_orden", to: "purchase_orders#crear_orden", as:"crear_orden"
  get 'formulario_agregar_detalle_orden', to: "purchase_orders#formulario_agregar_detalle_orden", as: "formulario_agregar_detalle_orden"
  post "/guardar_detalle_orden", to: "purchase_orders#guardar_detalle_orden", as:"guardar_detalle_orden"
  post '/guardar_total', to: "purchase_orders#guardar_total", as: "guardar_total"
  get 'eliminar_partida_orden/:id_partida', to:"purchase_orders#eliminar_partida_orden", as: "eliminar_partida_orden"
  get 'purchase_orders/:id/imprimir_orden', to: "purchase_orders#show", as: "imprimir_orden"
  
  #rutas presupuestos para venta
  get "/nuevo_presupuesto", to: "budget_concepts#nuevo_presupuesto", as:"nuevo_presupuesto"
  post "/crear_presupuesto", to: "budget_concepts#crear_presupuesto", as:"crear_presupuesto"
  get 'formulario_agregar_detalle', to: "budget_concepts#formulario_agregar_detalle", as: "formulario_agregar_detalle"
  post "/guardar_detalle", to: "budget_concepts#guardar_detalle", as:"guardar_detalle"
  get 'eliminar_partida/:id_partida', to:"budget_concepts#eliminar_partida", as: "eliminar_partida"
  get 'budget_concepts/:id/imprimir_pres', to: "budget_concepts#show", as: "presupuesto_pdf_imprimir"
  get 'solicitar_presupuesto_venta/:id', to: "budget_concepts#solicitar_presupuesto_venta", as: "solicitar_presupuesto_venta"
  get 'borrar_presupuesto_venta/:id',to: "budget_concepts#borrar_presupuesto_venta", as: "borrar_presupuesto_venta"
  
  # secciones- area
  get "/asignar_area/:id", to: "sections#asignar_area", as:"asignar_area"
  post "/guardar_area/:id", to: "sections#guardar_area", as:"guardar_area"
  get "/ver_areas/:id", to: "sections#ver_areas", as:"ver_areas"
  get 'borrar_area/:id_area,:id_section', to: "sections#borrar_area", as: "borrar_area"
  
  #rutas presupuestos para reparto
  get "/nuevo_pres_reparto", to: "budget_distributions#nuevo_pres_reparto", as:"nuevo_pres_reparto"
  post "/crear_presupuesto_reparto", to: "budget_distributions#crear_presupuesto_reparto", as:"crear_presupuesto_reparto"
  get 'formulario_agregar_detalle_reparto', to: "budget_distributions#formulario_agregar_detalle_reparto", as: "formulario_agregar_detalle_reparto"
  post "/guardar_detalle_reparto", to: "budget_distributions#guardar_detalle_reparto", as:"guardar_detalle_reparto"
  get 'eliminar_partida_reparto/:id_partida', to:"budget_distributions#eliminar_partida_reparto", as: "eliminar_partida_reparto"
  get 'budget_distributions/:id/imprimir', to: "budget_distributions#show", as: "presupuesto_imprimir"
  get 'solicitar_presupuesto_reparto/:id', to: "budget_distributions#solicitar_presupuesto_reparto", as: "solicitar_presupuesto_reparto"
  get 'borrar_presupuesto_reparto/:id',to: "budget_distributions#borrar_presupuesto_reparto", as: "borrar_presupuesto_reparto"
  
  #rutas presupuestos para administracion
  get "/nuevo_presupuesto_admin", to: "budget_administrations#nuevo_presupuesto_admin", as:"nuevo_presupuesto_admin"
  post "/crear_presupuesto_admin", to: "budget_administrations#crear_presupuesto_admin", as:"crear_presupuesto_admin"
  get 'solicitar_presupuesto_admin/:id', to: "budget_administrations#solicitar_presupuesto_admin", as: "solicitar_presupuesto_admin"
  get 'borrar_presupuesto_admin/:id',to: "budget_administrations#borrar_presupuesto_admin", as: "borrar_presupuesto_admin"
  
  #cargar factura 
  get 'documentos_factura/:id_consumo', to: "consumptions#documentos_factura", as: "documentos_factura"
  post 'cargar_factura', to: "consumptions#cargar_factura", as: "cargar_factura"
  get 'cancelar_encabezado/:folio', to: "consumptions#cancelar_encabezado", as: "cancelar_encabezado"
  get 'documentos_pdf/:id_consumo', to: "consumptions#documentos_pdf", as: "documentos_pdf"
  post 'cargar_pdf', to: "consumptions#cargar_pdf", as: "cargar_pdf"
  post 'solicitar_autorizacion/:folio', to: "consumptions#solicitar_autorizacion", as: "solicitar_autorizacion"
  post 'solicitar_autorizacion8/:folio', to: "consumptions#solicitar_autorizacion8", as: "solicitar_autorizacion8"
  post 'solicitar_autorizacion16/:folio', to: "consumptions#solicitar_autorizacion16", as: "solicitar_autorizacion16"
  get 'borrar_carga/:id',to: "consumptions#borrar_carga", as: "borrar_carga"

app/controllers/catalog_licences_controller.rb
class CatalogLicencesController < ApplicationController
  before_action :set_catalog_licence, only: [:show, :edit, :update, :destroy]
  before_action :validacion_menu
  # GET /catalog_licences
  # GET /catalog_licences.json
  def index
    session["usuario"] = ""
    session["vehiculo"] = ""
    @catalog_licences = CatalogLicence.consulta_licencias(session["usuario"],session["vehiculo"])
  end
 
  def filtrado_licencias
    session["usuario"] = params[:user_id]
    session["vehiculo"] = params[:vehicle_id]
    @catalog_licences = CatalogLicence.consulta_licencias(session["usuario"],session["vehiculo"])
    respond_to do |format|
      format.js
    end
  end
  # GET /catalog_licences/1
  # GET /catalog_licences/1.json
  def show
  end

  # GET /catalog_licences/new
  def new
    @catalog_licence = CatalogLicence.new
  end

  # GET /catalog_licences/1/edit
  def edit
  end

  # POST /catalog_licences
  # POST /catalog_licences.json
  def create
    begin
      @catalog_licence = CatalogLicence.new(catalog_licence_params)
      params[:catalog_licence][:vehicle_id] = params[:catalog_licence][:vehicle_id]
      respond_to do |format|
        if @catalog_licence.save
          #byebug
          #adjuntar_anverso = LicencesPicture.create(catalog_licence_id:  @catalog_licence.id,imagen: ruta,tipo:"Anverso",user_id: @catalog_licence.user_id,vehicle_id:  @catalog_licence.vehicle_id)
          format.html { redirect_to catalog_licences_path, notice: 'La licencia se creó con exito, favor de adjuntar las fotografias.' }
          format.json { render :show, status: :created, location: @catalog_licence }
        else
          format.html { render :new }
          format.json { render json: @catalog_licence.errors, status: :unprocessable_entity }
        end
      end
    rescue => exception
      redirect_to catalog_licences_path
      flash[:alert] = "Ocurrio un error, favor de contactar soporte. Error: #{exception}"
    end
  end

  # PATCH/PUT /catalog_licences/1
  # PATCH/PUT /catalog_licences/1.json
  def update
    begin
      respond_to do |format|
        if @catalog_licence.update(catalog_licence_params)
          format.html { redirect_to catalog_licences_path, notice: 'La licencia se actualizó con exito.' }
          format.json { render :show, status: :ok, location: @catalog_licence }
        else
          format.html { render :edit }
          format.json { render json: @catalog_licence.errors, status: :unprocessable_entity }
        end
      end
    rescue => exception
      redirect_to catalog_licences_path
      flash[:alert] = "Ocurrio un error, favor de contactar soporte. Error: #{exception}"
    end
  end

  # DELETE /catalog_licences/1
  # DELETE /catalog_licences/1.json
  def destroy
    @catalog_licence.destroy
    respond_to do |format|
      format.html { redirect_to catalog_licences_url, notice: 'La licencia se eliminó con exito.' }
      format.json { head :no_content }
    end
  end

  def fotos_anverso
    @documentos = CatalogLicence.where(id: params[:id])
    @documento = CatalogLicence.new
    @licencia_id = params[:id]
    respond_to do |format|
      format.js
    end
  end

  def cargar_fotos_anverso
    id_partida = params[:catalog_licence][:id]
    @documento = CatalogLicence.adjuntar_fotos_anverso(params, id_partida)
    @resultados = @documento
    @documentos = CatalogLicence.where(id: id_partida)
    @partida_id = id_partida
    if @documento[1] == 4
      flash[:notice] = @documento[0]
      redirect_to catalog_licences_url
    else
      @bandera_error = @documento[1]
      flash[:alert] = @documento[0]
      redirect_to catalog_licences_url
    end
  end
  def fotos_reverso
    @documentos = CatalogLicence.where(id: params[:id])
    @documento = CatalogLicence.new
    @licencia_id = params[:id]
    respond_to do |format|
      format.js
    end
  end

  def cargar_fotos_reverso
    id_partida = params[:catalog_licence][:id]
    @documento = CatalogLicence.adjuntar_fotos_reverso(params, id_partida)
    @resultados = @documento
    @documentos = CatalogLicence.where(id: id_partida)
    @partida_id = id_partida
    if @documento[1] == 4
      flash[:notice] = @documento[0]
      redirect_to catalog_licences_url
    else
      @bandera_error = @documento[1]
      flash[:alert] = @documento[0]
      redirect_to catalog_licences_url
    end
  end

  private
    def validacion_menu
      session["menu1"] = "Seguridad"
      session["menu2"] = "Catálogos"
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_catalog_licence
      @catalog_licence = CatalogLicence.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def catalog_licence_params
      params.require(:catalog_licence).permit(:clave, :descripcion,:numero_licencia,:fecha_vencimiento,:vehicle_id,:user_id)
    end
end

app/helpers/catalog_licences_helper.rb
module CatalogLicencesHelper
end

app/views/catalog_licences/_foto_anverso.html.erb
<div class="row">
    <% @documentos.each do |doc| %>
        <div class="col-lg-4">
            <div class="card bg-light" style="max-width: 100%; ">
                <div class="card-body">
                    <center>
                        <% if doc.anverso.attached? and doc.anverso.content_type == "application/pdf" %>
                            <embed src="<%= url_for(doc.anverso) %>" type="application/pdf" style="max-width: 100%; max-height:100px;" />
                            <br><br>
                            <%= link_to "Descargar", rails_blob_path(doc.anverso, disposition: 'attachment'), class: "btn btn-primary m-btn m-btn--custom" %>
                            <br><br>
                            <%#if doc.expenses_trips_expense.expenses_trip.status != "En comprobación" and doc.expenses_trips_expense.expenses_trip.status != "En revisión"%>
                                <%#= link_to "Eliminar", eliminar_documento_path(doc.id), class: "btn btn-danger m-btn m-btn--custom", data: {confirm: "¿Desea eliminar este documento?"}, remote: true %>
                            <%#end%>
                        <% elsif doc.anverso.attached? and (doc.anverso.content_type == "image/png" or doc.anverso.content_type == "image/jpg" or doc.anverso.content_type == "image/jpeg" or doc.anverso.content_type == "image/gif") %>
                            <%= image_tag doc.anverso, style: "max-height:100px; max-width:100%;" %>
                            <br><br>
                            <%= link_to "Descargar", rails_blob_path(doc.anverso, disposition: 'attachment'), class: "btn btn-primary m-btn m-btn--custom" %>
                            <br><br>
                            <%#if doc.expenses_trips_expense.expenses_trip.status != "En comprobación" and doc.expenses_trips_expense.expenses_trip.status != "En revisión"%>
                                <%#= link_to "Eliminar", eliminar_documento_path(doc.id), class: "btn btn-danger m-btn m-btn--custom", data: {confirm: "¿Desea eliminar este documento?"}, remote: true %>
                            <%#end%>
                        <% elsif doc.anverso.attached? %>
                            <h6><%= doc.anverso.filename %></h6>
                            <br>
                            <%= link_to "Descargar", rails_blob_path(doc.anverso, disposition: 'attachment'), class: "btn btn-primary m-btn m-btn--custom" %>
                            <br><br>
                            <%#if doc.expenses_trips_expense.expenses_trip.status != "En comprobación" and doc.expenses_trips_expense.expenses_trip.status != "En revisión"%>
                                <%#= link_to "Eliminar", eliminar_documento_path(doc.id), class: "btn btn-danger m-btn m-btn--custom", data: {confirm: "¿Desea eliminar este documento?"}, remote: true %>
                            <%#end%>
                        <% end %>  
                    </center>                  
                    <div class="row">                        
                        <div class="float-right">
                            <%#= link_to 'Editar', editar_reembolso_path(card.id), :class => "btn btn-primary m-btn m-btn--custom", style:'text-decoration:none' %>
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
    <% end %>
</div>    

app/views/catalog_licences/_foto_reverso.html.erb
<div class="row">
    <% @documentos.each do |doc| %>
        <div class="col-lg-4">
            <div class="card bg-light" style="max-width: 100%; ">
                <div class="card-body">
                    <center>
                        <% if doc.reverso.attached? and doc.reverso.content_type == "application/pdf" %>
                            <embed src="<%= url_for(doc.reverso) %>" type="application/pdf" style="max-width: 100%; max-height:100px;" />
                            <br><br>
                            <%= link_to "Descargar", rails_blob_path(doc.reverso, disposition: 'attachment'), class: "btn btn-primary m-btn m-btn--custom" %>
                            <br><br>
                            <%#if doc.expenses_trips_expense.expenses_trip.status != "En comprobación" and doc.expenses_trips_expense.expenses_trip.status != "En revisión"%>
                                <%#= link_to "Eliminar", eliminar_documento_path(doc.id), class: "btn btn-danger m-btn m-btn--custom", data: {confirm: "¿Desea eliminar este documento?"}, remote: true %>
                            <%#end%>
                        <% elsif doc.reverso.attached? and (doc.reverso.content_type == "image/png" or doc.reverso.content_type == "image/jpg" or doc.reverso.content_type == "image/jpeg" or doc.reverso.content_type == "image/gif") %>
                            <%= image_tag doc.reverso, style: "max-height:100px; max-width:100%;" %>
                            <br><br>
                            <%= link_to "Descargar", rails_blob_path(doc.reverso, disposition: 'attachment'), class: "btn btn-primary m-btn m-btn--custom" %>
                            <br><br>
                            <%#if doc.expenses_trips_expense.expenses_trip.status != "En comprobación" and doc.expenses_trips_expense.expenses_trip.status != "En revisión"%>
                                <%#= link_to "Eliminar", eliminar_documento_path(doc.id), class: "btn btn-danger m-btn m-btn--custom", data: {confirm: "¿Desea eliminar este documento?"}, remote: true %>
                            <%#end%>
                        <% elsif doc.reverso.attached? %>
                            <h6><%= doc.reverso.filename %></h6>
                            <br>
                            <%= link_to "Descargar", rails_blob_path(doc.reverso, disposition: 'attachment'), class: "btn btn-primary m-btn m-btn--custom" %>
                            <br><br>
                            <%#if doc.expenses_trips_expense.expenses_trip.status != "En comprobación" and doc.expenses_trips_expense.expenses_trip.status != "En revisión"%>
                                <%#= link_to "Eliminar", eliminar_documento_path(doc.id), class: "btn btn-danger m-btn m-btn--custom", data: {confirm: "¿Desea eliminar este documento?"}, remote: true %>
                            <%#end%>
                        <% end %>  
                    </center>                  
                    <div class="row">                        
                        <div class="float-right">
                            <%#= link_to 'Editar', editar_reembolso_path(card.id), :class => "btn btn-primary m-btn m-btn--custom", style:'text-decoration:none' %>
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
    <% end %>
</div>    

app/views/catalog_licences/_tabla.html.erb
<table class="table">
    <thead>
      <tr>
        <th>Clave</th>
        <th>Usuario</th>
        <th>No. Económico</th>
        <th>Tipo</th>
        <th>Número licencia</th>
        <th>Fecha vencimiento</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @catalog_licences.each do |catalog_licence| %>
        <tr>
          <td><%= catalog_licence.clave %></td>
          <td><%= catalog_licence.user.name %> <%= catalog_licence.user.last_name %></td>
          <td><%= catalog_licence.vehicle.numero_economico %></td>
          <td><%= catalog_licence.descripcion %></td>
          <td><%= catalog_licence.numero_licencia %></td>
          <td><%= l catalog_licence.fecha_vencimiento%></td>
          <td>
            <div class="dropdown dropdown-inline">
                <%= link_to fotos_anverso_path(catalog_licence.id),remote: true, title:"Adjuntar fotografía frontal" do%>
                    <span class='fas fa-address-card' style='font-size:16px;color:#A6ACAF'></span>
                    </span>
                <% end %>
            </div>
          </td>
          <td>
            <div class="dropdown dropdown-inline">
                <%= link_to fotos_reverso_path(catalog_licence.id),remote: true, title:"Adjuntar fotografía trasera" do%>
                    <span class='far fa-address-card' style='font-size:16px;color:#A6ACAF'></span>
                    </span>
                <% end %>
            </div>
          </td>
          <td>
            <div class="dropdown dropdown-inline">
              <%= link_to edit_catalog_licence_path(catalog_licence), title: "Editar" do %>
              <span class="svg-icon svg-icon-md"> 
              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px"
              viewBox="0 0 24 24" version="1.1">
              <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
              <rect x="0" y="0" width="24" height="24"></rect>
              <path d="M8,17.9148182 L8,5.96685884 C8,5.56391781 8.16211443,5.17792052 8.44982609,4.89581508 L10.965708,2.42895648 C11.5426798,1.86322723 12.4640974,1.85620921 13.0496196,2.41308426 L15.5337377,4.77566479 C15.8314604,5.0588212 16,5.45170806 16,5.86258077 L16,17.9148182 C16,18.7432453 15.3284271,19.4148182 14.5,19.4148182 L9.5,19.4148182 C8.67157288,19.4148182 8,18.7432453 8,17.9148182 Z"
              fill="#000000" fill-rule="nonzero" transform="translate(12.000000, 10.707409) rotate(-135.000000) translate(-12.000000, -10.707409) ">
              </path>
              <rect fill="#000000" opacity="0.3" x="5" y="20" width="15" height="2" rx="1"></rect>
              </g>
              </svg> 
              </span>
              <% end %>
              </div>
          </td>
        <td>
          <div class="dropdown dropdown-inline">
            <%= link_to catalog_licence, title:"Eliminar" ,method: :delete, data: { confirm: '¿Estas seguro?' } do %>
            <span class="svg-icon svg-icon-md"> <svg xmlns="http://www.w3.org/2000/svg"
            xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px"
              viewBox="0 0 24 24" version="1.1">
            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
              <rect x="0" y="0" width="24" height="24"></rect>
              <path d="M6,8 L6,20.5 C6,21.3284271 6.67157288,22 7.5,22 L16.5,22 C17.3284271,22 18,21.3284271 18,20.5 L18,8 L6,8 Z"
              fill="#000000" fill-rule="nonzero"></path>
              <path d="M14,4.5 L14,4 C14,3.44771525 13.5522847,3 13,3 L11,3 C10.4477153,3 10,3.44771525 10,4 L10,4.5 L5.5,4.5 C5.22385763,4.5 5,4.72385763 5,5 L5,5.5 C5,5.77614237 5.22385763,6 5.5,6 L18.5,6 C18.7761424,6 19,5.77614237 19,5.5 L19,5 C19,4.72385763 18.7761424,4.5 18.5,4.5 L14,4.5 Z"
              fill="#000000" opacity="0.3"></path>
              </g>
              </svg> </span>
            <% end %>
            </div>
        </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/catalog_licences/index.html.erb
<br>
<div class="container">
  <div class="card card-custom gutter-b">
  <div class="card-header">
    <div class="card-title">
      <h3 class="card-label">Licencias
      <span class="text-muted pt-2 font-size-sm d-block">Catálogo de licencias</span>
      </h3>
    </div>
    <div class="float-right">
      <br>
      <%= link_to 'Nuevo', new_catalog_licence_path,class:"btn btn-primary font-weight-bolder",style:"border-radius: 0.42rem;", data: { turbolinks: false } %>
    </div>
  </div>
  <div class="card-body">
      <%=form_for('', url: filtrado_licencias_path, remote: true) do |f|%>    <div class="container">
        <div class="row">
          <div class="col">
            <label class="col-sm-0 col-form-label" style="font-family: Arial; font-size:15px;">Usuario:</label>
            <%= collection_select('',:user_id ,User.listado_usuarios, :id, :nombre_completo, {prompt:"Seleccione un usuario"}, {:class => " form-control m-input m-input--air uneditable-input chosen-select",style: "width:100% !important;"})%>          </div>
          <div class="col">
            <label class="col-sm-0 col-form-label" style="font-family: Arial; font-size:15px;">No. Económico:</label>
            <%= collection_select('',:vehicle_id, Vehicle.listado_vehiculos, :id, :numero_economico, {prompt:"Seleccione el número"}, {:class => " form-control m-input m-input--air uneditable-input chosen-select"})%>
          </div>
          <div class="col">
            <br><br>
            <%= submit_tag "Buscar", class:"btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
    <br><br>
    <div style="width: 100%" id="table_container">
      <%= render  "tabla" %>
    </div>
    </div>
  </div>
</div>